### ISSUE TITLE
blank=True needed in image path in Sucursal model.

### ISSUE THREAD

**Issue by ghost** [UM-2021/speech-to-text-app#43]
![image](https://user-images.githubusercontent.com/80432953/121756771-a808a500-caf1-11eb-92b0-ef9ad1bd9c57.png)

**Comment by JFer11** [comment]
Gracias la sugerencia, fue solucionado y se realizó una mejora en como se guardaba la imagen, en la siguiente branch: https://github.com/UM-2021/speech-to-text-app/commit/eee385c50856ee4e21dfbe3fa31271a0c9c1f920
